server:
  port: 8888

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    hikari:
      username: root
      password: password
      connection-timeout: 1000
      minimum-idle: 10
      maximum-pool-size: 30
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    h2:
      username: root
      password: password
      driver-class-name: org.he.Driver
  h2:
    console:
      enabled: true
      path: /h2/console
      settings:
        web-admin-password: password
        trace: true
        web-allow-others: true
